### ISSUE TITLE
Viewport resizing

### ISSUE THREAD

**Issue by narc0tiq** [bullseyestudio/guns-game#12]
Currently, the client viewport is fixed-size (1024x576px). We should allow clients to resize their viewports, and should also have them notify the server of their viewport size.

The server should use this information to reduce the amount of data sent to each player -- if you can't see player A, you don't need to be told where they are (i.e. fog of war).

**Comment by Ethrel** [comment]
I have the client-side code implemented as well as the message to server, gotta work on server-side object culling yet. Should be up in the next few days. Hopefully. Once I wade through the relevant server code which I have barely touched yet.
