### ISSUE TITLE
Zoom levels

### ISSUE THREAD

**Issue by narc0tiq** [bullseyestudio/guns-game#18]
The client should support zooming in and out. The current view (as of rev 44865593dd5ac206349c1239887dfe1549244a0c) is a good example of the maximumly zoomed-in view. As max zoom-out with a default viewport size (1024x576), you'd want to see about 8x or 16x the number of map pixels.

**Comment by Ethrel** [comment]
Given I wrote the current client view code (or at least complicated it), I think this naturally follows next. Wish me luck :)

**Comment by Ethrel** [comment]
Once you pull #20, this is completed.

**Comment by narc0tiq** [comment]
Pulled in 559c61a, which closes this issue (awesome!!!)
