### ISSUE TITLE
Minor outstanding waypoint issues

### ISSUE THREAD

**Issue by narc0tiq** [bullseyestudio/guns-game#24]
- Server should tell clients about waypoints on connect
- Server should have a (console) command for listing waypoints
- and one for deleting waypoints
- and, while we're at it, one for setting waypoints
- think about deleting waypoints when owner disconnects? Currently leaning towards waypoints live forever.

One last thing to look at is some kind of making the waypoint ownership mechanism more explicit. Perhaps send an optional player id with player-owned waypoints, so a client can say "this waypoint is mine, it's the one I'll watch for delete requests".

**Comment by Ethrel** [comment]
Right-clicking on other waypoints removes your own waypoint. Is this intended behaviour or is it a bug?

**Comment by narc0tiq** [comment]
@Ethrel Yes, that's a bug, but it's not a server bug. On the other hand, it ties into the last paragraph in the issue, which is the cause of this bug.

**Comment by Ethrel** [comment]
@narc0tiq yes, I knew it wouldn't be a server bug. I was just wondering if it was _actually_ a bug or if you intentionally dropped that part of my code.

**Comment by narc0tiq** [comment]
Server-side, this is all done. Client will need one tiny fix to learn to keep track of its own waypoint.
