### ISSUE TITLE
Grid background for client

### ISSUE THREAD

**Issue by narc0tiq** [bullseyestudio/guns-game#27]
Should be a near-future thing -- some way for the player to tell they're actually moving!

**Comment by Ethrel** [comment]
...or we could get #14 working if even at a very messy and rudimentary level. Seems like that would be a better goal, as the grid would need to be replaced later anyway.

**Comment by narc0tiq** [comment]
@Ethrel Not necessarily, we can keep the grid indefinitely. It'd probably both look good as a design item and would still provide indication of movement in the (not impossible) case where the walls of the "room" on a given map are too far out of sight (and there is no visible rough terrain).

**Comment by narc0tiq** [comment]
Implemented; for the future, it should be made to show up only when actually in a battle, but it'll be fine as it is for a little while.
